// Generated by scripts/generate_growlybass_assets.py from the locked manifest.
// Do not edit by hand.
export const GROWLYBASS_SOURCE_COMMIT =
  '4f483268fc66b5a6d5781d421c0d11b8d08d3fc6';
export const GROWLYBASS_ANCHORS = [
  { name: 'e2', soundingMidi: 28 },
  { name: 'gb2', soundingMidi: 30 },
  { name: 'a2', soundingMidi: 33 },
  { name: 'c3', soundingMidi: 36 },
  { name: 'eb3', soundingMidi: 39 },
  { name: 'gb3', soundingMidi: 42 },
  { name: 'a3', soundingMidi: 45 },
  { name: 'c4', soundingMidi: 48 },
  { name: 'eb4', soundingMidi: 51 },
  { name: 'gb4', soundingMidi: 54 },
] as const;
export const GROWLYBASS_LAYERS = ['pp', 'p', 'f', 'ff'] as const;
